spring.application.name=authentication-service
server.port=8013

eureka.client.service-url.defaultZone=http://localhost:8012/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:mysql://localhost:3307/authentication-service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=authentication_user
spring.datasource.password=authentication_pass


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false